### ISSUE TITLE
rulr breaks on v12

### ISSUE THREAD

**Issue by moltar** [moltar/typescript-runtime-type-benchmarks#847]
```
Run ./start.sh
+ node -v
+ export NODE_VERSION=v12.22.10
+ npm start
> typescript-runtime-type-benchmarks@1.0.0 start /home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks
> ts-node index.ts
/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/node_modules/rulr/dist/rulr.modern.js:1
import{BaseError as r}from"make-error";import t from"validator";import e from"atob";class n extends r{constructor(){super("expected integer")}}function s(r){return Number.isInteger(r)}function o(r){if(s(r))return r;throw new n}class u extends r{constructor(){super("expected negative integer")}}function c(r){return s(r)&&r<=0}function i(r){if(c(r))return r;throw new u}class f extends r{constructor(){super("expected number")}}function a(r){return"number"==typeof r&&!1===Number.isNaN(r)}function p(r){if(a(r))return r;throw new f}class d extends r{constructor(){super("expected negative number")}}function h(r){return a(r)&&r<=0}function l(r){if(h(r))return r;throw new d}class w extends r{constructor(){super("expected positive integer")}}function x(r){return s(r)&&r>=0}function g(r){if(x(r))return r;throw new w}class m extends r{constructor(){super("expected positive number")}}function v(r){return a(r)&&r>=0}function y(r){if(v(r))return r;throw new m}class b extends r{constructor(){super("expected string")}}functio...
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/cases/rulr.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/node_modules/ts-node/src/index.ts:1056:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-runtime-type-benchmarks@1.0.0 start: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR! 
```

**Comment by hoeck** [comment]
Looks like a packaging issue with rulr to me.

Solutions I can think of:

1. some kind of "skip this library at this node-version" functionality
2. remove rulr from the benchmarks
3. file a bug bc. node12 being LTS may still be a valid target
4. fix it ourselves by hacking around the failing import somehow

**Comment by moltar** [comment]
Nice analysis, @hoeck.

I have started with (3): https://github.com/ryansmith94/rulr/issues/648

**Comment by moltar** [comment]
Then we can probably just move to (5), as I also don't see much difference between versions.

**Comment by hoeck** [comment]
Just checked it, node 12 end of life is [2022-04-30](https://nodejs.org/en/about/releases/) so yes, I'd also vote for (5).

Note to myself: do not forget to adjust the node-version in the [`pr.yml`](https://github.com/moltar/typescript-runtime-type-benchmarks/blob/7d2c544a49c111e3e826d10d321b008d0bf09d72/.github/workflows/pr.yml#L16) workflow too.

**Comment by ryansmith94** [comment]
Thanks guys 👍  Rulr should be fixed now.

**Comment by moltar** [comment]
@ryansmith94 thanks for looking at it.

But it seems to be still failing:


```
Run ./start.sh
+ node -v
+ export NODE_VERSION=v12.22.10
+ npm start

> typescript-runtime-type-benchmarks@1.0.0 start /home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks
> ts-node index.ts

/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/node_modules/rulr/dist/rulr.modern.js:1
import{BaseError as r}from"make-error";import t from"validator";import e from"atob";class n extends r{constructor(){super("expected integer")}}function s(r){return Number.isInteger(r)}function o(r){if(s(r))return r;throw new n}class u extends r{constructor(){super("expected negative integer")}}function c(r){return s(r)&&r<=0}function i(r){if(c(r))return r;throw new u}class f extends r{constructor(){super("expected number")}}function a(r){return"number"==typeof r&&!1===Number.isNaN(r)}function p(r){if(a(r))return r;throw new f}class d extends r{constructor(){super("expected negative number")}}function h(r){return a(r)&&r<=0}function l(r){if(h(r))return r;throw new d}class w extends r{constructor(){super("expected positive integer")}}function x(r){return s(r)&&r>=0}function g(r){if(x(r))return r;throw new w}class m extends r{constructor(){super("expected positive number")}}function v(r){return a(r)&&r>=0}function y(r){if(v(r))return r;throw new m}class b extends r{constructor(){super("expected string")}}function O(r){return"string"==typeof r}function E(r){if(O(r))return r;throw new b}class A extends r{constructor(){super("expected email")}}function N(r){return O(r)&&t.isEmail(r)}function J(r){if(N(r))return r;throw new A}class S extends r{constructor(){super("expected iri")}}const M=/^\w+:/i;function j(r){return O(r)&&M.test(r)}function k(r){if(j(r))return r;throw new S}class I extends r{constructor(){super("expected ISO 8601 Duration")}}const F=/^(-?)P(?=\d|T\d)(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)([DW]))?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?)?$/;function V(r){return O(r)&&F.test(r)}function T(r){if(V(r))return r;throw new I}class $ extends r{constructor(){super("expected ISO 8601 Timestamp")}}function L(r){return O(r)&&t.isISO8601(r,{strict:!0})}function D(r){if(L(r))return r;throw new $}class U extends r{constructor(){super("expected locale")}}function q(r){return O(r)&&t.isLocale(r)}function P(r){if(q(r))return r;throw new U}class R extends r{constructor(){super("expected mailto")}}const B=/^mailto:/;function C(r){return O(r)&&B.test(r)&&t.isEmail(r.replace(B,""))}function H(r){if(C(r))return r;throw new R}class Y extends r{constructor(){super("expected MIME type")}}function z(r){return O(r)&&t.isMimeType(r)}function W(r){if(z(r))return r;throw new Y}class Z extends r{constructor(){super("expected mongoId")}}function G(r){return O(r)&&t.isMongoId(r)}function K(r){if(G(r))return r;throw new Z}class Q extends r{constructor(r){super("expected value from enum"),this.enumValues=void 0,this.enumValues=r}}function X(r,t){return Object.values(r).includes(t)}function _(r){return t=>{if(X(r,t))return t;const e=Object.values(r);throw new Q(e)}}class rr extends r{constructor(){super("expected SCORM interaction type")}}var tr;function er(r){return X(tr,r)}function nr(r){if(er(r))return r;throw new rr}!function(r){r.TrueFalse="true-false",r.Choice="choice",r.FillIn="fill-in",r.LongFillIn="long-fill-in",r.Matching="matching",r.Performance="performance",r.Sequencing="sequencing",r.Likert="likert",r.Numeric="numeric",r.Other="other"}(tr||(tr={}));class sr extends r{constructor(){super("expected semantic version")}}function or(r){return O(r)&&t.isSemVer(r)}function ur(r){if(or(r))return r;throw new sr}class cr extends r{constructor(){super("expected sha1")}}function ir(r){return O(r)&&t.isHash(r,"sha1")}function fr(r){if(ir(r))return r;throw new cr}class ar extends r{constructor(){super("expected url")}}function pr(r){return O(r)&&t.isURL(r)}function dr(r){if(pr(r))return r;throw new ar}class hr extends r{constructor(){super("expected uuidv4")}}function lr(r){return O(r)&&t.isUUID(r,4)}function wr(r){if(lr(r))return r;throw new hr}function xr(r,t){return t}function gr(r){return t=>{try{return r(t),!0}catch(r){return!1}}}class mr extends r{constructor(r){super(r)}static getErrorsAsMessages(r){return r.map(r=>`${r.path.join(".")}: ${r.error instanceof Error?r.error.message:r.error}`)}static getErrorsAsMessage(r){return mr.getErrorsAsMessages(r).join("\n")}getMessages(){return mr.getErrorsAsMessages(this.toJSON())}}class vr extends mr{constructor(r){super(mr.getErrorsAsMessage(vr.getErrorsAsJson(r))),this.errors=void 0,this.errors=r}static getErrorsAsJson(r){return r.reduce((r,t)=>(r.push(...t.toJSON()),r),[])}toJSON(){return vr.getErrorsAsJson(this.errors)}}function yr(){return(yr=Object.assign||function(r){for(var t=1;t<arguments.length;t++){var e=arguments[t];for(var n in e)Object.prototype.hasOwnProperty.call(e,n)&&(r[n]=e[n])}return r}).apply(this,arguments)}class br extends mr{constructor(r,t,e){super(mr.getErrorsAsMessage(br.getErrorAsJson(r,t,e))),this.input=void 0,this.error=void 0,this.key=void 0,this.input=r,this.error=t,this.key=e}static getErrorAsJson(r,t,e){return t instanceof mr?t.toJSON().map(r=>yr({},r,{path:[e,...r.path]})):[{error:t,input:r,path:[e]}]}toJSON(){return br.getErrorAsJson(this.input,this.error,this.key)}}function Or(r){return null===r}function Er(r){return t=>Or(t)?t:r(t)}function Ar(r){return void 0===r}function Nr(r){return t=>Ar(t)?t:r(t)}class Jr extends r{constructor(){super("expected array")}}function Sr(r){if(Array.isArray(r))return r;throw new Jr}function Mr(r){return t=>{const e=Sr(t).reduce((t,e,n)=>{try{t.output[n]=r(e)}catch(r){t.errors.push(new br(e,r,n))}return t},{output:[],errors:[]});if(e.errors.length>0)throw new vr(e.errors);return e.output}}class jr extends r{constructor(){super("expected object")}}function kr(r){if("object"==typeof r&&null!==r&&r.constructor===Object)return r;throw new jr}function Ir(r){var t,e;const n=null!=(t=r.required)?t:{},s=null!=(e=r.optional)?e:{},o=function(r,t=!1){const e=Object.keys(r);return n=>e.reduce((e,s)=>{const o=n[s],u=r[s];try{e.output[s]=u(o)}catch(r){if(t)throw r;e.errors.push(new br(o,r,s))}return e},{output:{},errors:[]})}(n,r.bail),u=function(r,t=!1){const e=Object.keys(r);return n=>e.reduce((e,s)=>{const o=n[s],u=r[s];try{void 0!==o&&(e.output[s]=u(o))}catch(r){if(t)throw r;e.errors.push(new br(o,r,s))}return e},{output:{},errors:[]})}(s,r.bail);return r=>{const t=kr(r),e=o(t),n=u(t),s=[...e.errors,...n.errors];if(s.length>0)throw new vr(s);return yr({},e.output,n.output)}}class Fr extends br{constructor(r,t){super(t,r,t)}}function Vr(r,t){try{return{output:r(t)}}catch(r){return{error:r}}}function Tr(r,t){return e=>{const n=kr(e),s=Object.keys(n).reduce((e,s)=>{const o=n[s],u=Vr(r,s),c=Vr(t,o);return void 0===u.output||void 0===c.output?(void 0!==u.error&&void 0!==c.error?e.errors.push(new Fr(u.error,s),new br(o,c.error,s)):void 0!==u.error?e.errors.push(new Fr(u.error,s)):void 0!==c.error&&e.errors.push(new br(o,c.error,s)),e):(e.output[u.output]=c.output,e)},{output:{},errors:[]});if(s.errors.length>0)throw new vr(s.errors);return s.output}}function $r(...r){return t=>{const e=Sr(t),n=r.reduce((r,t,n)=>{const s=e[n];try{r.output[n]=t(s)}catch(t){r.errors.push(new br(s,t,n))}return r},{output:[],errors:[]});if(n.errors.length>0)throw new vr(n.errors);return n.output}}class Lr extends mr{constructor(r,t){super(mr.getErrorsAsMessage(Lr.getErrorsAsJson(r,t))),this.input=void 0,this.errors=void 0,this.input=r,this.errors=t}static getErrorsAsJson(r,t){return t.reduce((t,e)=>e instanceof mr?(t.push(...e.toJSON()),t):(t.push({error:e,input:r,path:[]}),t),[])}toJSON(){return Lr.getErrorsAsJson(this.input,this.errors)}}function Dr(...r){return t=>{const e=[];let n=null;if(r.some(r=>{try{return n=r(t),!0}catch(r){return e.push(r),!1}}))return n;throw new Lr(t,e)}}class Ur extends r{constructor(){super("expected basic auth from string")}}const qr=Ur,Pr=/^Basic [A-Za-z0-9+/=]+$/i,Rr="Basic ".length;function Br(r){return e(r.substr(Rr)).split(":")}function Cr(r){return O(r)&&Pr.test(r)&&2===Br(r).length}const Hr=Cr;class Yr{constructor(r,t){this.key=void 0,this.secret=void 0,this.key=r,this.secret=t}}function zr(r){if(O(r)&&Pr.test(r)){const t=Br(r);if(2===t.length)return new Yr(t[0],t[1])}throw new Ur}class Wr extends r{constructor(){super("expected boolean as string")}}const Zr=["true","TRUE","yes","YES","on","ON","1"],Gr=["false","FALSE","no","NO","off","OFF","0"];function Kr(r){return O(r)&&(Zr.includes(r)||Gr.includes(r))}function Qr(r){if(Kr(r))return Zr.includes(r);throw new Wr}const Xr=Qr;class _r extends r{constructor(){super("expected JSON as string")}}function rt(r){return O(r)&&function(r){try{return JSON.parse(r),!0}catch(r){return!1}}(r)}function tt(r){return t=>{if(O(t))return r(JSON.parse(t));throw new _r}}const et=tt;class nt extends r{constructor(){super("expected number as string")}}function st(r){return O(r)&&!Number.isNaN(parseFloat(r))}function ot(r){return t=>{if(st(t))return r(parseFloat(t));throw new nt}}const ut=ot;function ct(r){return r}class it extends r{constructor(){super("expected bigint")}}function ft(r){return"bigint"==typeof r}function at(r){if(ft(r))return r;throw new it}class pt extends r{constructor(){super("expected boolean")}}function dt(r){return"boolean"==typeof r}function ht(r){if(dt(r))return r;throw new pt}class lt extends r{constructor(r){super(`expected ${r}`),this.constantValue=void 0,this.constantValue=r}}function wt(r,t,e){return e===t}function xt(r,t){return r=>{if(wt(0,t,r))return r;throw new lt(t)}}class gt extends r{constructor(){super("expected date")}}function mt(r){return r instanceof Date}function vt(r){if(mt(r))return r;throw new gt}class yt extends r{constructor(r){super(`expected ${r}`),this.literalValue=void 0,this.literalValue=r}}function bt(r,t){return t===r}function Ot(r){return t=>{if(bt(r,t))return r;throw new yt(r)}}class Et extends r{constructor(){super("expected symbol")}}function At(r){return"symbol"==typeof r}function Nt(r){if(At(r))return r;throw new Et}function Jt(r){return r}export{Yr as BasicAuth,Fr as DictionaryKeyValidationError,Jr as InvalidArrayError,Ur as InvalidBasicAuthAsString,qr as InvalidBasicAuthFromString,it as InvalidBigIntError,Wr as InvalidBooleanAsStringError,pt as InvalidBooleanError,lt as InvalidConstantError,gt as InvalidDateError,A as InvalidEmailError,Q as InvalidEnumError,S as InvalidIRIError,I as InvalidISO8601DurationError,$ as InvalidISO8601TimestampError,n as InvalidIntegerError,_r as InvalidJsonAsStringError,yt as InvalidLiteralError,U as InvalidLocaleError,R as InvalidMailtoError,Y as InvalidMimeTypeError,Z as InvalidMongoIdError,u as InvalidNegativeIntegerError,d as InvalidNegativeNumberError,nt as InvalidNumberAsStringError,f as InvalidNumberError,jr as InvalidObjectError,w as InvalidPositiveIntegerError,m as InvalidPositiveNumberError,cr as InvalidSHA1Error,rr as InvalidScormInteractionTypeError,sr as InvalidSemanticVersionError,b as InvalidStringError,Et as InvalidSymbolError,ar as InvalidURLError,hr as InvalidUUIDV4Error,br as KeyedValidationError,tr as ScormInteractionType,Lr as UnionValidationError,mr as ValidationError,vr as ValidationErrors,Er as allowNull,Nr as allowUndefined,ct as any,Mr as array,at as bigint,ht as boolean,xt as constant,xr as constrain,vt as date,Tr as dictionary,J as email,_ as enumerated,Gr as falsyBooleanStrings,gr as guard,o as integer,k as iri,Cr as isBasicAuthAsString,Hr as isBasicAuthFromString,ft as isBigInt,dt as isBoolean,Kr as isBooleanAsString,wt as isConstant,mt as isDate,N as isEmail,X as isEnum,j as isIRI,V as isISO8601Duration,L as isISO8601Timestamp,s as isInteger,rt as isJsonAsString,bt as isLiteral,q as isLocale,C as isMailto,z as isMimeType,G as isMongoId,c as isNegativeInteger,h as isNegativeNumber,Or as isNull,a as isNumber,st as isNumberAsString,x as isPositiveInteger,v as isPositiveNumber,ir as isSHA1,er as isScormInteractionType,or as isSemanticVersion,O as isString,At as isSymbol,pr as isURL,lr as isUUIDV4,Ar as isUndefined,T as iso8601Duration,D as iso8601Timestamp,Ot as literal,P as locale,H as mailto,W as mimeType,K as mongoId,i as negativeInteger,l as negativeNumber,p as number,Ir as object,g as positiveInteger,y as positiveNumber,zr as sanitizeBasicAuthFromString,Xr as sanitizeBooleanAsString,Qr as sanitizeBooleanFromString,et as sanitizeJsonAsString,tt as sanitizeJsonFromString,ut as sanitizeNumberAsString,ot as sanitizeNumberFromString,nr as scormInteractionType,ur as semanticVersion,fr as sha1,E as string,Nt as symbol,Zr as truthyBooleanStrings,$r as tuple,Dr as union,Jt as unknown,dr as url,wr as uuidv4};
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/cases/rulr.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/home/runner/work/typescript-runtime-type-benchmarks/typescript-runtime-type-benchmarks/node_modules/ts-node/src/index.ts:1056:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-runtime-type-benchmarks@1.0.0 start: `ts-node index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-runtime-type-benchmarks@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-22T02_49_23_680Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by ryansmith94** [comment]
Ah damn, sorry guys, just cloning this repo to see what's happening, it's working okay in one of our repos so I don't think to check it with this one.

**Comment by ryansmith94** [comment]
Okay, figured it out, when we re-added Rulr to master in ce1393008297faf82355838142810ae32c7b984b, we didn't upgrade the package to pull in the fix from [Rulr v8.7.3](https://github.com/ryansmith94/rulr/releases/tag/v8.7.3). I've created #853 to resolve the issue.

**Comment by moltar** [comment]
> we didn't upgrade the package to pull in the fix

Oh, duhh! 🙈
